#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.C28_float{1,0,17.6,0
#
sysbiosLab6F28335.x28FP: package/cfg/sysbiosLab6F28335.x28FP.mak

clean::
	-$(RM) package/cfg/sysbiosLab6F28335.x28FP.mak
