#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.C28_float{1,0,17.6,0
#
f28335McBSPasSPI.x28FP: package/cfg/f28335McBSPasSPI.x28FP.mak

clean::
	-$(RM) package/cfg/f28335McBSPasSPI.x28FP.mak
