#ifndef _COECSL_REGISTERS_H_
#define _COECSL_REGISTERS_H_

/*
six LEDS
								GPIO2.5
								GPIO2.6
								GPIO2.8
								GPIO2.19
								GPIO2.20
								GPIO2.24

3 switches						GPIO2.26
								GPIO2.27
								GPIO2.28
								
HWI interrupt GPIO2.25 could be switch but not currently

COLOR LCD RESET  				?

Flags:
DATA_FROM_LINUX 				GPIO2.0
DATA_TO_LINUX 					GPIO2.1
VBDATA_FROM_LINUX				GPIO2.2 
VBDATA_TO_LINUX					GPIO2.3

*****NEW FLAGS FOR LINUX ASTAR PATH AND MAP*****
ASTAR_COMMAND					GPIO2.4
ASTAR_FAILED					GPIO8.0
ASTAR_DONE						GPIO8.23 

LINUX_BOOTED					GPIO7.3
IMAGE_TO_LINUX 					GPIO7.5
OPTITRACKDATA_FROM_LINUX		GPIO7.6
DATAFORFILE_TO_LINUX 			GPIO7.17


Unused and can be used for flags:
GPIO7.30
GPIO7.31
*/
#define GPIO7_DATAIN *(volatile unsigned int*)(0x48051138) 
#define GPIO8_DATAIN *(volatile unsigned int*)(0x48053138)
#define GPIO2_DATAIN *(volatile unsigned int*)(0x48055138)
#define GPIO7_DATAOUT *(volatile unsigned int*)(0x4805113C)
#define GPIO8_DATAOUT *(volatile unsigned int*)(0x4805313C)
#define GPIO2_DATAOUT *(volatile unsigned int*)(0x4805513C)

								
#define SETLED1 (GPIO2_DATAOUT |= (1<<5))
#define SETLED2 (GPIO2_DATAOUT |= (1<<6))
#define SETLED3 (GPIO2_DATAOUT |= (1<<8))
#define SETLED4 (GPIO2_DATAOUT |= (1<<19))
#define SETLED5 (GPIO2_DATAOUT |= (1<<20))
#define SETLED6 (GPIO2_DATAOUT |= (1<<24))

#define CLRLED1 (GPIO2_DATAOUT &= ~(1<<5))
#define CLRLED2 (GPIO2_DATAOUT &= ~(1<<6))
#define CLRLED3 (GPIO2_DATAOUT &= ~(1<<8))
#define CLRLED4 (GPIO2_DATAOUT &= ~(1<<19))
#define CLRLED5 (GPIO2_DATAOUT &= ~(1<<20))
#define CLRLED6 (GPIO2_DATAOUT &= ~(1<<24))

#define GETLED1STATE ((GPIO2_DATAOUT>>5) & 0x1)
#define GETLED2STATE ((GPIO2_DATAOUT>>6) & 0x1)
#define GETLED3STATE ((GPIO2_DATAOUT>>8) & 0x1)
#define GETLED4STATE ((GPIO2_DATAOUT>>19) & 0x1)
#define GETLED5STATE ((GPIO2_DATAOUT>>20) & 0x1)
#define GETLED6STATE ((GPIO2_DATAOUT>>24) & 0x1)

#define GETSWITCH1 ((GPIO2_DATAIN>>26) & 0x1)
#define GETSWITCH2 ((GPIO2_DATAIN>>27) & 0x1)
#define GETSWITCH3 ((GPIO2_DATAIN>>28) & 0x1)

//OPTITRACKDATA_FROM_LINUX		GPIO7.6
#define SET_OPTITRACKDATA_FROM_LINUX (GPIO7_DATAOUT |= (1<<6))
#define CLR_OPTITRACKDATA_FROM_LINUX (GPIO7_DATAOUT &= ~(1<<6))
#define GET_OPTITRACKDATA_FROM_LINUX ((GPIO7_DATAOUT>>6) & 0x1)

//DATA_FROM_LINUX 				GPIO2.0
#define SET_DATA_FROM_LINUX (GPIO2_DATAOUT |= (1<<0))
#define CLR_DATA_FROM_LINUX (GPIO2_DATAOUT &= ~(1<<0))
#define GET_DATA_FROM_LINUX ((GPIO2_DATAOUT>>0) & 0x1)

//LVDATA_FROM_LINUX				GPIO2.2 
#define SET_LVDATA_FROM_LINUX (GPIO2_DATAOUT |= (1<<2))
#define CLR_LVDATA_FROM_LINUX (GPIO2_DATAOUT &= ~(1<<2))
#define GET_LVDATA_FROM_LINUX ((GPIO2_DATAOUT>>2) & 0x1)

//LVDATA_TO_LINUX					GPIO2.3
#define SET_LVDATA_TO_LINUX (GPIO2_DATAOUT |= (1<<3))
#define CLR_LVDATA_TO_LINUX (GPIO2_DATAOUT &= ~(1<<3))
#define GET_LVDATA_TO_LINUX ((GPIO2_DATAOUT>>3) & 0x1)

//DATA_TO_LINUX 					GPIO2.1
#define SET_DATA_TO_LINUX (GPIO2_DATAOUT |= (1<<1))
#define CLR_DATA_TO_LINUX (GPIO2_DATAOUT &= ~(1<<1))
#define GET_DATA_TO_LINUX ((GPIO2_DATAOUT>>1) & 0x1)

//IMAGE_TO_LINUX 					GPIO7.5
#define SET_IMAGE_TO_LINUX (GPIO7_DATAOUT |= (1<<5))
#define CLR_IMAGE_TO_LINUX (GPIO7_DATAOUT &= ~(1<<5))
#define GET_IMAGE_TO_LINUX ((GPIO7_DATAOUT>>5) & 0x1)

//LINUX_BOOTED					GPIO7.3
#define SET_LINUX_BOOTED (GPIO7_DATAOUT |= (1<<3))
#define CLR_LINUX_BOOTED (GPIO7_DATAOUT &= ~(1<<3))
#define GET_LINUX_BOOTED ((GPIO7_DATAOUT>>3) & 0x1)

//DATAFORFILE_TO_LINUX 			GPIO7.17
#define SET_DATAFORFILE_TO_LINUX (GPIO7_DATAOUT |= (1<<17))
#define CLR_DATAFORFILE_TO_LINUX (GPIO7_DATAOUT &= ~(1<<17))
#define GET_DATAFORFILE_TO_LINUX ((GPIO7_DATAOUT>>17) & 0x1)

//ASTAR_COMMAND					GPIO2.4
#define SET_ASTAR_COMMAND (GPIO2_DATAOUT |= (1<<4))
#define CLR_ASTAR_COMMAND (GPIO2_DATAOUT &= ~(1<<4))
#define GET_ASTAR_COMMAND ((GPIO2_DATAOUT>>4) & 0x1)

//ASTAR_FAILED					GPIO8.0
#define SET_ASTAR_FAILED (GPIO8_DATAOUT |= (1<<0))
#define CLR_ASTAR_FAILED (GPIO8_DATAOUT &= ~(1<<0))
#define GET_ASTAR_FAILED ((GPIO8_DATAOUT>>0) & 0x1)

//ASTAR_DONE						GPIO8.23 
#define SET_ASTAR_DONE (GPIO8_DATAOUT |= (1<<23))
#define CLR_ASTAR_DONE (GPIO8_DATAOUT &= ~(1<<23))
#define GET_ASTAR_DONE ((GPIO8_DATAOUT>>23) & 0x1)

#endif /* _COECSL_REGISTERS_H_ */
